// pancake-fleet-server protocol.
//
// VMs call Enroll on boot to register themselves with the fleet.
// Operators (or background workers) call list/attest RPCs to inspect
// + verify the fleet.
//
// Pancaked on each VM already exposes the Attest RPC (see orchpb).
// The fleet server is the orchestrator-side aggregator: it discovers
// VMs (auto-registered via Enroll), polls them for attestations,
// stores results in PostgreSQL, and surfaces the data via the web UI.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // unique VM identifier (hostname or GCE instance name)
	Platform          string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // "self-hosted", "gce", ...
	InternalIp        string                 `protobuf:"bytes,3,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	ExternalIp        string                 `protobuf:"bytes,4,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"` // optional
	CertSerial        string                 `protobuf:"bytes,5,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"` // PEM serial number, hex
	CertExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cert_expires_at,json=certExpiresAt,proto3" json:"cert_expires_at,omitempty"`
	CurrentGeneration int32                  `protobuf:"varint,7,opt,name=current_generation,json=currentGeneration,proto3" json:"current_generation,omitempty"`
	// metadata is a JSON blob (string-encoded) for platform-specific
	// info (e.g. GCE labels, instance ID). Stored as JSONB.
	MetadataJson string `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// ek_pub is the TPM2B_PUBLIC blob of the VM's endorsement key
	// (contents of /etc/pancake/ek.pub from the VM). The fleet server
	// stores this at first enrollment (TOFU) and verifies subsequent
	// attestations bytes-match — locking the VM to the same vTPM it
	// first registered with. On Shielded VMs the API call to
	// getShieldedInstanceIdentity at first boot is the trust anchor
	// for THIS specific ekPub; subsequent attestations are equality-
	// checked against the recorded value.
	EkPub         []byte `protobuf:"bytes,9,opt,name=ek_pub,json=ekPub,proto3" json:"ek_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnrollRequest) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *EnrollRequest) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *EnrollRequest) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *EnrollRequest) GetCertExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiresAt
	}
	return nil
}

func (x *EnrollRequest) GetCurrentGeneration() int32 {
	if x != nil {
		return x.CurrentGeneration
	}
	return 0
}

func (x *EnrollRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *EnrollRequest) GetEkPub() []byte {
	if x != nil {
		return x.EkPub
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // assigned vm id
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CurrentGeneration int32                  `protobuf:"varint,2,opt,name=current_generation,json=currentGeneration,proto3" json:"current_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentGeneration() int32 {
	if x != nil {
		return x.CurrentGeneration
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{3}
}

type ListVMsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by platform ("gce", "self-hosted", ""=all)
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Filter by attestation status ("valid", "failed", "never", "quarantined", ""=all)
	AttestationStatus string `protobuf:"bytes,2,opt,name=attestation_status,json=attestationStatus,proto3" json:"attestation_status,omitempty"`
	// Pagination
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // default 100, max 1000
	PageToken     int32 `protobuf:"varint,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // offset; 0 = first page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *ListVMsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListVMsRequest) GetAttestationStatus() string {
	if x != nil {
		return x.AttestationStatus
	}
	return ""
}

func (x *ListVMsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVMsRequest) GetPageToken() int32 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VM                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	NextPageToken int32                  `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 0 = no more pages
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *ListVMsResponse) GetVms() []*VM {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *ListVMsResponse) GetNextPageToken() int32 {
	if x != nil {
		return x.NextPageToken
	}
	return 0
}

func (x *ListVMsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*GetVMRequest_Name
	//	*GetVMRequest_VmId
	Id            isGetVMRequest_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *GetVMRequest) GetId() isGetVMRequest_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetVMRequest) GetName() string {
	if x != nil {
		if x, ok := x.Id.(*GetVMRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *GetVMRequest) GetVmId() int32 {
	if x != nil {
		if x, ok := x.Id.(*GetVMRequest_VmId); ok {
			return x.VmId
		}
	}
	return 0
}

type isGetVMRequest_Id interface {
	isGetVMRequest_Id()
}

type GetVMRequest_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type GetVMRequest_VmId struct {
	VmId int32 `protobuf:"varint,2,opt,name=vm_id,json=vmId,proto3,oneof"`
}

func (*GetVMRequest_Name) isGetVMRequest_Id() {}

func (*GetVMRequest_VmId) isGetVMRequest_Id() {}

type VM struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform          string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	InternalIp        string                 `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	ExternalIp        string                 `protobuf:"bytes,5,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	EnrolledAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	CertSerial        string                 `protobuf:"bytes,7,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	CertExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=cert_expires_at,json=certExpiresAt,proto3" json:"cert_expires_at,omitempty"`
	LastHeartbeat     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	LastAttestation   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_attestation,json=lastAttestation,proto3" json:"last_attestation,omitempty"`
	AttestationStatus string                 `protobuf:"bytes,11,opt,name=attestation_status,json=attestationStatus,proto3" json:"attestation_status,omitempty"`
	CurrentGeneration int32                  `protobuf:"varint,12,opt,name=current_generation,json=currentGeneration,proto3" json:"current_generation,omitempty"`
	MetadataJson      string                 `protobuf:"bytes,13,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VM) Reset() {
	*x = VM{}
	mi := &file_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *VM) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VM) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VM) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *VM) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *VM) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

func (x *VM) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *VM) GetCertExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiresAt
	}
	return nil
}

func (x *VM) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *VM) GetLastAttestation() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttestation
	}
	return nil
}

func (x *VM) GetAttestationStatus() string {
	if x != nil {
		return x.AttestationStatus
	}
	return ""
}

func (x *VM) GetCurrentGeneration() int32 {
	if x != nil {
		return x.CurrentGeneration
	}
	return 0
}

func (x *VM) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\x10pancake.fleet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n" +
	"\rEnrollRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vinternal_ip\x18\x03 \x01(\tR\n" +
	"internalIp\x12\x1f\n" +
	"\vexternal_ip\x18\x04 \x01(\tR\n" +
	"externalIp\x12\x1f\n" +
	"\vcert_serial\x18\x05 \x01(\tR\n" +
	"certSerial\x12B\n" +
	"\x0fcert_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rcertExpiresAt\x12-\n" +
	"\x12current_generation\x18\a \x01(\x05R\x11currentGeneration\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12\x15\n" +
	"\x06ek_pub\x18\t \x01(\fR\x05ekPub\":\n" +
	"\x0eEnrollResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12current_generation\x18\x02 \x01(\x05R\x11currentGeneration\"\x13\n" +
	"\x11HeartbeatResponse\"\x97\x01\n" +
	"\x0eListVMsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12-\n" +
	"\x12attestation_status\x18\x02 \x01(\tR\x11attestationStatus\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\x05R\tpageToken\"w\n" +
	"\x0fListVMsResponse\x12&\n" +
	"\x03vms\x18\x01 \x03(\v2\x14.pancake.fleet.v1.VMR\x03vms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\x05R\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"A\n" +
	"\fGetVMRequest\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x15\n" +
	"\x05vm_id\x18\x02 \x01(\x05H\x00R\x04vmIdB\x04\n" +
	"\x02id\"\xb5\x04\n" +
	"\x02VM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vinternal_ip\x18\x04 \x01(\tR\n" +
	"internalIp\x12\x1f\n" +
	"\vexternal_ip\x18\x05 \x01(\tR\n" +
	"externalIp\x12;\n" +
	"\venrolled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\x12\x1f\n" +
	"\vcert_serial\x18\a \x01(\tR\n" +
	"certSerial\x12B\n" +
	"\x0fcert_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rcertExpiresAt\x12A\n" +
	"\x0elast_heartbeat\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12E\n" +
	"\x10last_attestation\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastAttestation\x12-\n" +
	"\x12attestation_status\x18\v \x01(\tR\x11attestationStatus\x12-\n" +
	"\x12current_generation\x18\f \x01(\x05R\x11currentGeneration\x12#\n" +
	"\rmetadata_json\x18\r \x01(\tR\fmetadataJson2\xc0\x02\n" +
	"\fFleetManager\x12K\n" +
	"\x06Enroll\x12\x1f.pancake.fleet.v1.EnrollRequest\x1a .pancake.fleet.v1.EnrollResponse\x12T\n" +
	"\tHeartbeat\x12\".pancake.fleet.v1.HeartbeatRequest\x1a#.pancake.fleet.v1.HeartbeatResponse\x12N\n" +
	"\aListVMs\x12 .pancake.fleet.v1.ListVMsRequest\x1a!.pancake.fleet.v1.ListVMsResponse\x12=\n" +
	"\x05GetVM\x12\x1e.pancake.fleet.v1.GetVMRequest\x1a\x14.pancake.fleet.v1.VMB=Z;github.com/sinkap/pancake/tools/pancake-go/internal/fleetpbb\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fleet_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: pancake.fleet.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: pancake.fleet.v1.EnrollResponse
	(*HeartbeatRequest)(nil),      // 2: pancake.fleet.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: pancake.fleet.v1.HeartbeatResponse
	(*ListVMsRequest)(nil),        // 4: pancake.fleet.v1.ListVMsRequest
	(*ListVMsResponse)(nil),       // 5: pancake.fleet.v1.ListVMsResponse
	(*GetVMRequest)(nil),          // 6: pancake.fleet.v1.GetVMRequest
	(*VM)(nil),                    // 7: pancake.fleet.v1.VM
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_fleet_proto_depIdxs = []int32{
	8,  // 0: pancake.fleet.v1.EnrollRequest.cert_expires_at:type_name -> google.protobuf.Timestamp
	7,  // 1: pancake.fleet.v1.ListVMsResponse.vms:type_name -> pancake.fleet.v1.VM
	8,  // 2: pancake.fleet.v1.VM.enrolled_at:type_name -> google.protobuf.Timestamp
	8,  // 3: pancake.fleet.v1.VM.cert_expires_at:type_name -> google.protobuf.Timestamp
	8,  // 4: pancake.fleet.v1.VM.last_heartbeat:type_name -> google.protobuf.Timestamp
	8,  // 5: pancake.fleet.v1.VM.last_attestation:type_name -> google.protobuf.Timestamp
	0,  // 6: pancake.fleet.v1.FleetManager.Enroll:input_type -> pancake.fleet.v1.EnrollRequest
	2,  // 7: pancake.fleet.v1.FleetManager.Heartbeat:input_type -> pancake.fleet.v1.HeartbeatRequest
	4,  // 8: pancake.fleet.v1.FleetManager.ListVMs:input_type -> pancake.fleet.v1.ListVMsRequest
	6,  // 9: pancake.fleet.v1.FleetManager.GetVM:input_type -> pancake.fleet.v1.GetVMRequest
	1,  // 10: pancake.fleet.v1.FleetManager.Enroll:output_type -> pancake.fleet.v1.EnrollResponse
	3,  // 11: pancake.fleet.v1.FleetManager.Heartbeat:output_type -> pancake.fleet.v1.HeartbeatResponse
	5,  // 12: pancake.fleet.v1.FleetManager.ListVMs:output_type -> pancake.fleet.v1.ListVMsResponse
	7,  // 13: pancake.fleet.v1.FleetManager.GetVM:output_type -> pancake.fleet.v1.VM
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	file_fleet_proto_msgTypes[6].OneofWrappers = []any{
		(*GetVMRequest_Name)(nil),
		(*GetVMRequest_VmId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
