// pancake-os build daemon protocol.        *** PROPOSAL, not wired up ***
//
// pancake-build-server runs centrally on an orchestrator host. It does the
// heavy work that today happens on every client (`pancake bootstrap`
// on the build host, `pancake install`/`pancake update` inside a VM):
//
//   - mmdebstrap / apt-get download
//   - per-package overlay-snapshot + dpkg --unpack/--configure
//   - mkfs.ext4 + veritysetup → image.img + image.hash + roothash
//   - manifest.toml synthesis, signed with one of the daemon's keys
//
// Clients call BuildLayer/LookupLayer/GetLayer over gRPC. The daemon
// caches every built layer on disk forever, keyed by roothash; the
// reverse index from (pkg, version, suite, arch) → roothash is used
// to short-circuit BuildLayer when the result is already known.
//
// The roothash IS the layer's identity. Two BuildLayer calls with the
// same spec MUST return the same roothash (assuming the underlying
// .deb hasn't been re-uploaded upstream). This sidesteps the
// mkfs.ext4-reproducibility problem from the client-side build path
// (existing task #33): there is exactly one build per layer, done by
// the daemon, cached forever — clients never rebuild, they download.
//
// Trust:
//   - Each LayerHandle carries a manifest.toml + manifest.sig where
//     the sig is RSA-PKCS1v15-SHA256 over manifest.toml under one of
//     the daemon's signing keys (selected by signing_key_id).
//   - The roothash inside the manifest.toml is the cryptographic
//     identity of image.img (verity root). Clients re-verify on
//     receipt: bytes are streamed → veritysetup format → compare
//     against manifest.toml's roothash.
//   - This means GetLayer transport can be untrusted (bytes are
//     content-addressed). But BuildLayer/BuildGeneration/UploadBlob
//     are bearer-token authenticated (same systemd-creds sealed
//     pattern as pancaked uses today; see DefaultSealedTokenPath in
//     internal/orchsrv).
//
// Out of scope for this service:
//   - `pancake-host` layer. Per-host by definition; clients build it
//     locally from inputs they shouldn't send to a shared cache.
//     Contents (post-rework):
//       /etc/hostname
//       /etc/machine-id                   (placeholder; systemd
//                                          regenerates at first boot)
//       /etc/ssh/ssh_host_*_key{,.pub}
//       /etc/ssh/sshd_config
//       /root/.ssh/authorized_keys
//       /etc/resolv.conf
//       /etc/systemd/network/10-wired.network
//   - The orchestrator-side "push manifest to a fleet of VMs"
//     workflow lives in the existing orchpb Pancake service.
//     pancake-build-server produces the manifest; orchpb pushes it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/buildpb/build.proto

package buildpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LayerPart int32

const (
	LayerPart_LAYER_PART_UNSPECIFIED LayerPart = 0
	LayerPart_LAYER_PART_IMAGE       LayerPart = 1 // image.img (data + verity tree)
	LayerPart_LAYER_PART_HASH        LayerPart = 2 // image.hash (verity hash tree)
	LayerPart_LAYER_PART_MANIFEST    LayerPart = 3 // manifest.toml + manifest_sig
	LayerPart_LAYER_PART_ROOTHASH    LayerPart = 4 // image.roothash sidecar (one line)
)

// Enum value maps for LayerPart.
var (
	LayerPart_name = map[int32]string{
		0: "LAYER_PART_UNSPECIFIED",
		1: "LAYER_PART_IMAGE",
		2: "LAYER_PART_HASH",
		3: "LAYER_PART_MANIFEST",
		4: "LAYER_PART_ROOTHASH",
	}
	LayerPart_value = map[string]int32{
		"LAYER_PART_UNSPECIFIED": 0,
		"LAYER_PART_IMAGE":       1,
		"LAYER_PART_HASH":        2,
		"LAYER_PART_MANIFEST":    3,
		"LAYER_PART_ROOTHASH":    4,
	}
)

func (x LayerPart) Enum() *LayerPart {
	p := new(LayerPart)
	*p = x
	return p
}

func (x LayerPart) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerPart) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_buildpb_build_proto_enumTypes[0].Descriptor()
}

func (LayerPart) Type() protoreflect.EnumType {
	return &file_internal_buildpb_build_proto_enumTypes[0]
}

func (x LayerPart) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerPart.Descriptor instead.
func (LayerPart) EnumDescriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{0}
}

type Package struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Manager:
	//
	//	*Package_Apt
	//	*Package_Internal
	Manager       isPackage_Manager `protobuf_oneof:"manager"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_internal_buildpb_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetManager() isPackage_Manager {
	if x != nil {
		return x.Manager
	}
	return nil
}

func (x *Package) GetApt() *APT {
	if x != nil {
		if x, ok := x.Manager.(*Package_Apt); ok {
			return x.Apt
		}
	}
	return nil
}

func (x *Package) GetInternal() *PancakeInternal {
	if x != nil {
		if x, ok := x.Manager.(*Package_Internal); ok {
			return x.Internal
		}
	}
	return nil
}

type isPackage_Manager interface {
	isPackage_Manager()
}

type Package_Apt struct {
	Apt *APT `protobuf:"bytes,1,opt,name=apt,proto3,oneof"`
}

type Package_Internal struct {
	Internal *PancakeInternal `protobuf:"bytes,2,opt,name=internal,proto3,oneof"` // future: RPM rpm = 3;  Snap snap = 4;  ...
}

func (*Package_Apt) isPackage_Manager() {}

func (*Package_Internal) isPackage_Manager() {}

type APT struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // "openssh-server" — required
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // "1:9.6p1-3ubuntu13.16" — empty = suite latest
	// (server pins the resolved version into the
	// returned manifest's [package].version)
	Suite         string `protobuf:"bytes,3,opt,name=suite,proto3" json:"suite,omitempty"`   // "noble" — required
	Arch          string `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`     // "amd64" — empty defaults to "amd64"
	Mirror        string `protobuf:"bytes,5,opt,name=mirror,proto3" json:"mirror,omitempty"` // optional override for the apt mirror URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APT) Reset() {
	*x = APT{}
	mi := &file_internal_buildpb_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APT) ProtoMessage() {}

func (x *APT) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APT.ProtoReflect.Descriptor instead.
func (*APT) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{1}
}

func (x *APT) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APT) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *APT) GetSuite() string {
	if x != nil {
		return x.Suite
	}
	return ""
}

func (x *APT) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *APT) GetMirror() string {
	if x != nil {
		return x.Mirror
	}
	return ""
}

// PancakeInternal is "a package built by pancake itself" — a
// synthetic layer that doesn't come from any third-party package
// manager. The set of valid internal layer kinds is data-driven,
// not schema-encoded: each kind is a `recipe` name registered
// server-side and described in a text-proto catalog (see
// internal_layers.textproto). Adding a new internal layer = a data
// change in the catalog + a builder handler in Go, with no .proto
// edit.
//
// pancake-host is NOT a recipe here — it's per-host (see file
// header) and built client-side.
//
// Today the registered recipes are:
//
//	recipe="base"
//	  "Cross-cutting baseline files for a package set" — the ~36
//	  files no individual .deb owns: identity tables (passwd/shadow/
//	  group), PAM common-* configs, netbase defaults (/etc/hosts,
//	  /etc/networks), base-files defaults (/etc/profile, /etc/fstab,
//	  etc.).
//	  Inputs:  packages (required, sorted; suite/arch on each entry,
//	           all entries must share suite + arch).
//	  Roothash: function of sorted package list.
//
//	recipe="runtime"
//	  "pancake CLI + helpers + systemd units" — the pancake layer.
//	  Contents: /usr/local/bin/pancake, /usr/sbin/{mount-overlay,
//	  pivot-root}, /etc/systemd/system/pancake-{debug,state-rw,
//	  ldconfig,hwdb}.service (+ MUTW symlinks), and optional
//	  /etc/pancake/manifest.pubkey.
//	  Inputs:  blobs["pancake-binary"]        required
//	           blobs["mount-overlay-binary"]  required
//	           blobs["pivot-root-binary"]     required
//	           blobs["manifest-pubkey"]       optional
//
//	recipe="kernel"
//	  "/boot/vmlinuz from an uploaded bzImage."
//	  Inputs:  version           required
//	           blobs["bzimage"]  required
//
//	recipe="modules"
//	  "/lib/modules/<ver> from an uploaded tarball."
//	  Inputs:  version           required
//	           blobs["tarball"]  required
//
//	recipe="pancaked"
//	  "/usr/sbin/pancaked + systemd unit."
//	  Inputs:  version           required
//	           blobs["binary"]   required
//
// Per-layer roothash semantics: bytes-identical inputs → identical
// roothash, so the cache works the same way as for APT layers.
//
// The two services in the runtime layer worth calling out:
//   - pancake-ldconfig.service runs `ldconfig` at early boot to
//     regenerate /etc/ld.so.cache in the writable overlay (avoids
//     shipping it in any verity layer — its content depends on
//     libraries from every layer).
//   - pancake-hwdb.service runs `systemd-hwdb update` to regenerate
//     /usr/lib/udev/hwdb.bin in the overlay (12 MiB savings vs.
//     shipping it).
//
// Build-time-only packages (apt, dpkg, libapt-pkg6.0t64, gpgv,
// debian-archive-keyring) are installed into the sandbox during the
// "base" recipe's build but produce no layer of their own; their
// files are also stripped from the base layer.
type PancakeInternal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipe name. Must match a recipe registered in the server's
	// catalog. Server returns INVALID_ARGUMENT if unknown, or if the
	// inputs don't satisfy the recipe's required/optional fields.
	Recipe string `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	// Inputs. Which fields a given recipe consumes is determined by
	// the recipe definition; unused fields must be empty.
	Packages      []*APT            `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`                                                                     // recipes that take a pkg set
	Blobs         map[string]string `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // role-name → sha256 (from UploadBlob)
	Version       string            `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                                                       // recipes that take a version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PancakeInternal) Reset() {
	*x = PancakeInternal{}
	mi := &file_internal_buildpb_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PancakeInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PancakeInternal) ProtoMessage() {}

func (x *PancakeInternal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PancakeInternal.ProtoReflect.Descriptor instead.
func (*PancakeInternal) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{2}
}

func (x *PancakeInternal) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

func (x *PancakeInternal) GetPackages() []*APT {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PancakeInternal) GetBlobs() map[string]string {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *PancakeInternal) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// LayerHandle is the server's response to a successful build/lookup.
// It carries the signed manifest bytes plus convenience scalars so
// callers don't have to parse TOML for the common case.
type LayerHandle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical identity. The client uses this for GetLayer and as the
	// primary key in its local cache (kit/repo/<roothash>/ would be a
	// sane on-disk layout; today's <pkg>-<slug> is preserved as a
	// friendly secondary index — see `name`/`version` below).
	Roothash string `protobuf:"bytes,1,opt,name=roothash,proto3" json:"roothash,omitempty"`
	// Signed per-layer manifest. manifest_sig is RSA-PKCS1v15-SHA256
	// over manifest_toml under signing_key_id.
	ManifestToml []byte `protobuf:"bytes,2,opt,name=manifest_toml,json=manifestToml,proto3" json:"manifest_toml,omitempty"`
	ManifestSig  []byte `protobuf:"bytes,3,opt,name=manifest_sig,json=manifestSig,proto3" json:"manifest_sig,omitempty"`
	SigningKeyId string `protobuf:"bytes,4,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	// Convenience (parsed from manifest_toml; redundant but lets clients
	// skip TOML parsing for `pancake list`-style enumeration):
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	DataSize      int64                  `protobuf:"varint,8,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"` // image.img bytes
	HashSize      int64                  `protobuf:"varint,9,opt,name=hash_size,json=hashSize,proto3" json:"hash_size,omitempty"` // image.hash bytes
	BuiltAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerHandle) Reset() {
	*x = LayerHandle{}
	mi := &file_internal_buildpb_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerHandle) ProtoMessage() {}

func (x *LayerHandle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerHandle.ProtoReflect.Descriptor instead.
func (*LayerHandle) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{3}
}

func (x *LayerHandle) GetRoothash() string {
	if x != nil {
		return x.Roothash
	}
	return ""
}

func (x *LayerHandle) GetManifestToml() []byte {
	if x != nil {
		return x.ManifestToml
	}
	return nil
}

func (x *LayerHandle) GetManifestSig() []byte {
	if x != nil {
		return x.ManifestSig
	}
	return nil
}

func (x *LayerHandle) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *LayerHandle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayerHandle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LayerHandle) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *LayerHandle) GetDataSize() int64 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *LayerHandle) GetHashSize() int64 {
	if x != nil {
		return x.HashSize
	}
	return 0
}

func (x *LayerHandle) GetBuiltAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuiltAt
	}
	return nil
}

type BuildLayerRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Package *Package               `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// Optional: name of one of the daemon's signing keys to sign with.
	// Empty = the daemon's default key. The chosen key's pubkey must be
	// enrolled at the client (typically via initramfs-baked
	// /etc/pancake/manifest.pubkey).
	SigningKeyId  string `protobuf:"bytes,2,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLayerRequest) Reset() {
	*x = BuildLayerRequest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLayerRequest) ProtoMessage() {}

func (x *BuildLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLayerRequest.ProtoReflect.Descriptor instead.
func (*BuildLayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{4}
}

func (x *BuildLayerRequest) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *BuildLayerRequest) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

type LookupLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *Package               `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupLayerRequest) Reset() {
	*x = LookupLayerRequest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupLayerRequest) ProtoMessage() {}

func (x *LookupLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupLayerRequest.ProtoReflect.Descriptor instead.
func (*LookupLayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{5}
}

func (x *LookupLayerRequest) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type BuildGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Packages in DESIRED OVERLAY ORDER (leftmost wins). Server builds
	// each (or pulls from cache) and assembles them into a generation
	// manifest in the same order.
	Packages      []*Package `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Parent        int32      `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`   // 0 = new lineage
	Counter       int32      `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"` // 0 = server picks (max(prev)+1)
	Description   string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SigningKeyId  string     `protobuf:"bytes,5,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildGenerationRequest) Reset() {
	*x = BuildGenerationRequest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildGenerationRequest) ProtoMessage() {}

func (x *BuildGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildGenerationRequest.ProtoReflect.Descriptor instead.
func (*BuildGenerationRequest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{6}
}

func (x *BuildGenerationRequest) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *BuildGenerationRequest) GetParent() int32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *BuildGenerationRequest) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *BuildGenerationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BuildGenerationRequest) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

// GenerationManifest: the bytes the VM writes to generations/<id>/.
// Same wire shape as orchpb.Manifest so it can be passed straight to
// orchpb.Pancake.Update.
type GenerationManifest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ManifestToml []byte                 `protobuf:"bytes,1,opt,name=manifest_toml,json=manifestToml,proto3" json:"manifest_toml,omitempty"`
	ManifestSig  []byte                 `protobuf:"bytes,2,opt,name=manifest_sig,json=manifestSig,proto3" json:"manifest_sig,omitempty"`
	Lowers       []byte                 `protobuf:"bytes,3,opt,name=lowers,proto3" json:"lowers,omitempty"`
	// Convenience: a handle for each layer the manifest references, in
	// overlay order. Lets callers prefetch missing bytes at the
	// destination via GetLayer.
	Layer         []*LayerHandle `protobuf:"bytes,4,rep,name=layer,proto3" json:"layer,omitempty"`
	GenerationId  int32          `protobuf:"varint,5,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	Counter       int32          `protobuf:"varint,6,opt,name=counter,proto3" json:"counter,omitempty"`
	SigningKeyId  string         `protobuf:"bytes,7,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationManifest) Reset() {
	*x = GenerationManifest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationManifest) ProtoMessage() {}

func (x *GenerationManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationManifest.ProtoReflect.Descriptor instead.
func (*GenerationManifest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{7}
}

func (x *GenerationManifest) GetManifestToml() []byte {
	if x != nil {
		return x.ManifestToml
	}
	return nil
}

func (x *GenerationManifest) GetManifestSig() []byte {
	if x != nil {
		return x.ManifestSig
	}
	return nil
}

func (x *GenerationManifest) GetLowers() []byte {
	if x != nil {
		return x.Lowers
	}
	return nil
}

func (x *GenerationManifest) GetLayer() []*LayerHandle {
	if x != nil {
		return x.Layer
	}
	return nil
}

func (x *GenerationManifest) GetGenerationId() int32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *GenerationManifest) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *GenerationManifest) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

type GetLayerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Roothash string                 `protobuf:"bytes,1,opt,name=roothash,proto3" json:"roothash,omitempty"`
	// Resumable transfer. offset/length apply to the IMAGE part only;
	// HASH/MANIFEST/ROOTHASH parts are always sent in full.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length int64 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 0 = until end
	// Subset of parts to send. Empty = all four.
	Want          []LayerPart `protobuf:"varint,4,rep,packed,name=want,proto3,enum=pancake.build.v1.LayerPart" json:"want,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLayerRequest) Reset() {
	*x = GetLayerRequest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayerRequest) ProtoMessage() {}

func (x *GetLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayerRequest.ProtoReflect.Descriptor instead.
func (*GetLayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{8}
}

func (x *GetLayerRequest) GetRoothash() string {
	if x != nil {
		return x.Roothash
	}
	return ""
}

func (x *GetLayerRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetLayerRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetLayerRequest) GetWant() []LayerPart {
	if x != nil {
		return x.Want
	}
	return nil
}

type LayerChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Part  LayerPart              `protobuf:"varint,1,opt,name=part,proto3,enum=pancake.build.v1.LayerPart" json:"part,omitempty"`
	Data  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Last  bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"` // last chunk for this part
	// For LAYER_PART_IMAGE: file offset where `data` begins. Server
	// walks the cached image.img with SEEK_DATA/SEEK_HOLE and only
	// sends data ranges; clients use WriteAt(data, offset) and a
	// final Truncate(DataSize) to recreate the sparse file. Saves
	// ~3× wire bandwidth + on-disk size for large ext4 images that
	// are mostly hole. For other parts (HASH/MANIFEST/ROOTHASH),
	// offset is ignored and chunks are sent contiguously.
	Offset        int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerChunk) Reset() {
	*x = LayerChunk{}
	mi := &file_internal_buildpb_build_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerChunk) ProtoMessage() {}

func (x *LayerChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerChunk.ProtoReflect.Descriptor instead.
func (*LayerChunk) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{9}
}

func (x *LayerChunk) GetPart() LayerPart {
	if x != nil {
		return x.Part
	}
	return LayerPart_LAYER_PART_UNSPECIFIED
}

func (x *LayerChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LayerChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *LayerChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListLayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamePrefix    string                 `protobuf:"bytes,1,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"` // empty = no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayersRequest) Reset() {
	*x = ListLayersRequest{}
	mi := &file_internal_buildpb_build_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayersRequest) ProtoMessage() {}

func (x *ListLayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayersRequest.ProtoReflect.Descriptor instead.
func (*ListLayersRequest) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{10}
}

func (x *ListLayersRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

type ListLayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         []*LayerHandle         `protobuf:"bytes,1,rep,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayersResponse) Reset() {
	*x = ListLayersResponse{}
	mi := &file_internal_buildpb_build_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayersResponse) ProtoMessage() {}

func (x *ListLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayersResponse.ProtoReflect.Descriptor instead.
func (*ListLayersResponse) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{11}
}

func (x *ListLayersResponse) GetLayer() []*LayerHandle {
	if x != nil {
		return x.Layer
	}
	return nil
}

type BlobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	mi := &file_internal_buildpb_build_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{12}
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlobChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type BlobReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobReference) Reset() {
	*x = BlobReference{}
	mi := &file_internal_buildpb_build_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobReference) ProtoMessage() {}

func (x *BlobReference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobReference.ProtoReflect.Descriptor instead.
func (*BlobReference) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{13}
}

func (x *BlobReference) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BlobReference) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        []*Recipe              `protobuf:"bytes,1,rep,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_internal_buildpb_build_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{14}
}

func (x *Catalog) GetRecipe() []*Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type Recipe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipe name. Matches PancakeInternal.recipe on the wire.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Which inputs the recipe consumes. The server enforces:
	//   - if requires_packages, PancakeInternal.packages must be non-empty
	//   - if requires_version,  PancakeInternal.version  must be non-empty
	//   - every required_blobs role must have an entry in
	//     PancakeInternal.blobs; optional_blobs may or may not
	//   - any blob role NOT in required_blobs ∪ optional_blobs is an error
	RequiresPackages bool     `protobuf:"varint,3,opt,name=requires_packages,json=requiresPackages,proto3" json:"requires_packages,omitempty"`
	RequiresVersion  bool     `protobuf:"varint,4,opt,name=requires_version,json=requiresVersion,proto3" json:"requires_version,omitempty"`
	RequiredBlobs    []string `protobuf:"bytes,5,rep,name=required_blobs,json=requiredBlobs,proto3" json:"required_blobs,omitempty"`
	OptionalBlobs    []string `protobuf:"bytes,6,rep,name=optional_blobs,json=optionalBlobs,proto3" json:"optional_blobs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_internal_buildpb_build_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_internal_buildpb_build_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_internal_buildpb_build_proto_rawDescGZIP(), []int{15}
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetRequiresPackages() bool {
	if x != nil {
		return x.RequiresPackages
	}
	return false
}

func (x *Recipe) GetRequiresVersion() bool {
	if x != nil {
		return x.RequiresVersion
	}
	return false
}

func (x *Recipe) GetRequiredBlobs() []string {
	if x != nil {
		return x.RequiredBlobs
	}
	return nil
}

func (x *Recipe) GetOptionalBlobs() []string {
	if x != nil {
		return x.OptionalBlobs
	}
	return nil
}

var File_internal_buildpb_build_proto protoreflect.FileDescriptor

const file_internal_buildpb_build_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/buildpb/build.proto\x12\x10pancake.build.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\aPackage\x12)\n" +
	"\x03apt\x18\x01 \x01(\v2\x15.pancake.build.v1.APTH\x00R\x03apt\x12?\n" +
	"\binternal\x18\x02 \x01(\v2!.pancake.build.v1.PancakeInternalH\x00R\binternalB\t\n" +
	"\amanager\"u\n" +
	"\x03APT\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05suite\x18\x03 \x01(\tR\x05suite\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06mirror\x18\x05 \x01(\tR\x06mirror\"\xf4\x01\n" +
	"\x0fPancakeInternal\x12\x16\n" +
	"\x06recipe\x18\x01 \x01(\tR\x06recipe\x121\n" +
	"\bpackages\x18\x02 \x03(\v2\x15.pancake.build.v1.APTR\bpackages\x12B\n" +
	"\x05blobs\x18\x03 \x03(\v2,.pancake.build.v1.PancakeInternal.BlobsEntryR\x05blobs\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x1a8\n" +
	"\n" +
	"BlobsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x02\n" +
	"\vLayerHandle\x12\x1a\n" +
	"\broothash\x18\x01 \x01(\tR\broothash\x12#\n" +
	"\rmanifest_toml\x18\x02 \x01(\fR\fmanifestToml\x12!\n" +
	"\fmanifest_sig\x18\x03 \x01(\fR\vmanifestSig\x12$\n" +
	"\x0esigning_key_id\x18\x04 \x01(\tR\fsigningKeyId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12\x1b\n" +
	"\tdata_size\x18\b \x01(\x03R\bdataSize\x12\x1b\n" +
	"\thash_size\x18\t \x01(\x03R\bhashSize\x125\n" +
	"\bbuilt_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\abuiltAt\"n\n" +
	"\x11BuildLayerRequest\x123\n" +
	"\apackage\x18\x01 \x01(\v2\x19.pancake.build.v1.PackageR\apackage\x12$\n" +
	"\x0esigning_key_id\x18\x02 \x01(\tR\fsigningKeyId\"I\n" +
	"\x12LookupLayerRequest\x123\n" +
	"\apackage\x18\x01 \x01(\v2\x19.pancake.build.v1.PackageR\apackage\"\xc9\x01\n" +
	"\x16BuildGenerationRequest\x125\n" +
	"\bpackages\x18\x01 \x03(\v2\x19.pancake.build.v1.PackageR\bpackages\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x05R\x06parent\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x05R\acounter\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\x0esigning_key_id\x18\x05 \x01(\tR\fsigningKeyId\"\x8e\x02\n" +
	"\x12GenerationManifest\x12#\n" +
	"\rmanifest_toml\x18\x01 \x01(\fR\fmanifestToml\x12!\n" +
	"\fmanifest_sig\x18\x02 \x01(\fR\vmanifestSig\x12\x16\n" +
	"\x06lowers\x18\x03 \x01(\fR\x06lowers\x123\n" +
	"\x05layer\x18\x04 \x03(\v2\x1d.pancake.build.v1.LayerHandleR\x05layer\x12#\n" +
	"\rgeneration_id\x18\x05 \x01(\x05R\fgenerationId\x12\x18\n" +
	"\acounter\x18\x06 \x01(\x05R\acounter\x12$\n" +
	"\x0esigning_key_id\x18\a \x01(\tR\fsigningKeyId\"\x8e\x01\n" +
	"\x0fGetLayerRequest\x12\x1a\n" +
	"\broothash\x18\x01 \x01(\tR\broothash\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12/\n" +
	"\x04want\x18\x04 \x03(\x0e2\x1b.pancake.build.v1.LayerPartR\x04want\"}\n" +
	"\n" +
	"LayerChunk\x12/\n" +
	"\x04part\x18\x01 \x01(\x0e2\x1b.pancake.build.v1.LayerPartR\x04part\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"4\n" +
	"\x11ListLayersRequest\x12\x1f\n" +
	"\vname_prefix\x18\x01 \x01(\tR\n" +
	"namePrefix\"I\n" +
	"\x12ListLayersResponse\x123\n" +
	"\x05layer\x18\x01 \x03(\v2\x1d.pancake.build.v1.LayerHandleR\x05layer\"3\n" +
	"\tBlobChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last\";\n" +
	"\rBlobReference\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\";\n" +
	"\aCatalog\x120\n" +
	"\x06recipe\x18\x01 \x03(\v2\x18.pancake.build.v1.RecipeR\x06recipe\"\xe4\x01\n" +
	"\x06Recipe\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11requires_packages\x18\x03 \x01(\bR\x10requiresPackages\x12)\n" +
	"\x10requires_version\x18\x04 \x01(\bR\x0frequiresVersion\x12%\n" +
	"\x0erequired_blobs\x18\x05 \x03(\tR\rrequiredBlobs\x12%\n" +
	"\x0eoptional_blobs\x18\x06 \x03(\tR\roptionalBlobs*\x84\x01\n" +
	"\tLayerPart\x12\x1a\n" +
	"\x16LAYER_PART_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LAYER_PART_IMAGE\x10\x01\x12\x13\n" +
	"\x0fLAYER_PART_HASH\x10\x02\x12\x17\n" +
	"\x13LAYER_PART_MANIFEST\x10\x03\x12\x17\n" +
	"\x13LAYER_PART_ROOTHASH\x10\x042\x8f\x04\n" +
	"\x0ePancakeBuilder\x12P\n" +
	"\n" +
	"BuildLayer\x12#.pancake.build.v1.BuildLayerRequest\x1a\x1d.pancake.build.v1.LayerHandle\x12R\n" +
	"\vLookupLayer\x12$.pancake.build.v1.LookupLayerRequest\x1a\x1d.pancake.build.v1.LayerHandle\x12a\n" +
	"\x0fBuildGeneration\x12(.pancake.build.v1.BuildGenerationRequest\x1a$.pancake.build.v1.GenerationManifest\x12M\n" +
	"\bGetLayer\x12!.pancake.build.v1.GetLayerRequest\x1a\x1c.pancake.build.v1.LayerChunk0\x01\x12L\n" +
	"\n" +
	"UploadBlob\x12\x1b.pancake.build.v1.BlobChunk\x1a\x1f.pancake.build.v1.BlobReference(\x01\x12W\n" +
	"\n" +
	"ListLayers\x12#.pancake.build.v1.ListLayersRequest\x1a$.pancake.build.v1.ListLayersResponseB=Z;github.com/sinkap/pancake/tools/pancake-go/internal/buildpbb\x06proto3"

var (
	file_internal_buildpb_build_proto_rawDescOnce sync.Once
	file_internal_buildpb_build_proto_rawDescData []byte
)

func file_internal_buildpb_build_proto_rawDescGZIP() []byte {
	file_internal_buildpb_build_proto_rawDescOnce.Do(func() {
		file_internal_buildpb_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_buildpb_build_proto_rawDesc), len(file_internal_buildpb_build_proto_rawDesc)))
	})
	return file_internal_buildpb_build_proto_rawDescData
}

var file_internal_buildpb_build_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_buildpb_build_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_buildpb_build_proto_goTypes = []any{
	(LayerPart)(0),                 // 0: pancake.build.v1.LayerPart
	(*Package)(nil),                // 1: pancake.build.v1.Package
	(*APT)(nil),                    // 2: pancake.build.v1.APT
	(*PancakeInternal)(nil),        // 3: pancake.build.v1.PancakeInternal
	(*LayerHandle)(nil),            // 4: pancake.build.v1.LayerHandle
	(*BuildLayerRequest)(nil),      // 5: pancake.build.v1.BuildLayerRequest
	(*LookupLayerRequest)(nil),     // 6: pancake.build.v1.LookupLayerRequest
	(*BuildGenerationRequest)(nil), // 7: pancake.build.v1.BuildGenerationRequest
	(*GenerationManifest)(nil),     // 8: pancake.build.v1.GenerationManifest
	(*GetLayerRequest)(nil),        // 9: pancake.build.v1.GetLayerRequest
	(*LayerChunk)(nil),             // 10: pancake.build.v1.LayerChunk
	(*ListLayersRequest)(nil),      // 11: pancake.build.v1.ListLayersRequest
	(*ListLayersResponse)(nil),     // 12: pancake.build.v1.ListLayersResponse
	(*BlobChunk)(nil),              // 13: pancake.build.v1.BlobChunk
	(*BlobReference)(nil),          // 14: pancake.build.v1.BlobReference
	(*Catalog)(nil),                // 15: pancake.build.v1.Catalog
	(*Recipe)(nil),                 // 16: pancake.build.v1.Recipe
	nil,                            // 17: pancake.build.v1.PancakeInternal.BlobsEntry
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_internal_buildpb_build_proto_depIdxs = []int32{
	2,  // 0: pancake.build.v1.Package.apt:type_name -> pancake.build.v1.APT
	3,  // 1: pancake.build.v1.Package.internal:type_name -> pancake.build.v1.PancakeInternal
	2,  // 2: pancake.build.v1.PancakeInternal.packages:type_name -> pancake.build.v1.APT
	17, // 3: pancake.build.v1.PancakeInternal.blobs:type_name -> pancake.build.v1.PancakeInternal.BlobsEntry
	18, // 4: pancake.build.v1.LayerHandle.built_at:type_name -> google.protobuf.Timestamp
	1,  // 5: pancake.build.v1.BuildLayerRequest.package:type_name -> pancake.build.v1.Package
	1,  // 6: pancake.build.v1.LookupLayerRequest.package:type_name -> pancake.build.v1.Package
	1,  // 7: pancake.build.v1.BuildGenerationRequest.packages:type_name -> pancake.build.v1.Package
	4,  // 8: pancake.build.v1.GenerationManifest.layer:type_name -> pancake.build.v1.LayerHandle
	0,  // 9: pancake.build.v1.GetLayerRequest.want:type_name -> pancake.build.v1.LayerPart
	0,  // 10: pancake.build.v1.LayerChunk.part:type_name -> pancake.build.v1.LayerPart
	4,  // 11: pancake.build.v1.ListLayersResponse.layer:type_name -> pancake.build.v1.LayerHandle
	16, // 12: pancake.build.v1.Catalog.recipe:type_name -> pancake.build.v1.Recipe
	5,  // 13: pancake.build.v1.PancakeBuilder.BuildLayer:input_type -> pancake.build.v1.BuildLayerRequest
	6,  // 14: pancake.build.v1.PancakeBuilder.LookupLayer:input_type -> pancake.build.v1.LookupLayerRequest
	7,  // 15: pancake.build.v1.PancakeBuilder.BuildGeneration:input_type -> pancake.build.v1.BuildGenerationRequest
	9,  // 16: pancake.build.v1.PancakeBuilder.GetLayer:input_type -> pancake.build.v1.GetLayerRequest
	13, // 17: pancake.build.v1.PancakeBuilder.UploadBlob:input_type -> pancake.build.v1.BlobChunk
	11, // 18: pancake.build.v1.PancakeBuilder.ListLayers:input_type -> pancake.build.v1.ListLayersRequest
	4,  // 19: pancake.build.v1.PancakeBuilder.BuildLayer:output_type -> pancake.build.v1.LayerHandle
	4,  // 20: pancake.build.v1.PancakeBuilder.LookupLayer:output_type -> pancake.build.v1.LayerHandle
	8,  // 21: pancake.build.v1.PancakeBuilder.BuildGeneration:output_type -> pancake.build.v1.GenerationManifest
	10, // 22: pancake.build.v1.PancakeBuilder.GetLayer:output_type -> pancake.build.v1.LayerChunk
	14, // 23: pancake.build.v1.PancakeBuilder.UploadBlob:output_type -> pancake.build.v1.BlobReference
	12, // 24: pancake.build.v1.PancakeBuilder.ListLayers:output_type -> pancake.build.v1.ListLayersResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_buildpb_build_proto_init() }
func file_internal_buildpb_build_proto_init() {
	if File_internal_buildpb_build_proto != nil {
		return
	}
	file_internal_buildpb_build_proto_msgTypes[0].OneofWrappers = []any{
		(*Package_Apt)(nil),
		(*Package_Internal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_buildpb_build_proto_rawDesc), len(file_internal_buildpb_build_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_buildpb_build_proto_goTypes,
		DependencyIndexes: file_internal_buildpb_build_proto_depIdxs,
		EnumInfos:         file_internal_buildpb_build_proto_enumTypes,
		MessageInfos:      file_internal_buildpb_build_proto_msgTypes,
	}.Build()
	File_internal_buildpb_build_proto = out.File
	file_internal_buildpb_build_proto_goTypes = nil
	file_internal_buildpb_build_proto_depIdxs = nil
}
