// pancake-os build daemon protocol.        *** PROPOSAL, not wired up ***
//
// pancake-build-server runs centrally on an orchestrator host. It does the
// heavy work that today happens on every client (`pancake bootstrap`
// on the build host, `pancake install`/`pancake update` inside a VM):
//
//   - mmdebstrap / apt-get download
//   - per-package overlay-snapshot + dpkg --unpack/--configure
//   - mkfs.ext4 + veritysetup → image.img + image.hash + roothash
//   - manifest.toml synthesis, signed with one of the daemon's keys
//
// Clients call BuildLayer/LookupLayer/GetLayer over gRPC. The daemon
// caches every built layer on disk forever, keyed by roothash; the
// reverse index from (pkg, version, suite, arch) → roothash is used
// to short-circuit BuildLayer when the result is already known.
//
// The roothash IS the layer's identity. Two BuildLayer calls with the
// same spec MUST return the same roothash (assuming the underlying
// .deb hasn't been re-uploaded upstream). This sidesteps the
// mkfs.ext4-reproducibility problem from the client-side build path
// (existing task #33): there is exactly one build per layer, done by
// the daemon, cached forever — clients never rebuild, they download.
//
// Trust:
//   - Each LayerHandle carries a manifest.toml + manifest.sig where
//     the sig is RSA-PKCS1v15-SHA256 over manifest.toml under one of
//     the daemon's signing keys (selected by signing_key_id).
//   - The roothash inside the manifest.toml is the cryptographic
//     identity of image.img (verity root). Clients re-verify on
//     receipt: bytes are streamed → veritysetup format → compare
//     against manifest.toml's roothash.
//   - This means GetLayer transport can be untrusted (bytes are
//     content-addressed). But BuildLayer/BuildGeneration/UploadBlob
//     are bearer-token authenticated (same systemd-creds sealed
//     pattern as pancaked uses today; see DefaultSealedTokenPath in
//     internal/orchsrv).
//
// Out of scope for this service:
//   - `pancake-host` layer. Per-host by definition; clients build it
//     locally from inputs they shouldn't send to a shared cache.
//     Contents (post-rework):
//       /etc/hostname
//       /etc/machine-id                   (placeholder; systemd
//                                          regenerates at first boot)
//       /etc/ssh/ssh_host_*_key{,.pub}
//       /etc/ssh/sshd_config
//       /root/.ssh/authorized_keys
//       /etc/resolv.conf
//       /etc/systemd/network/10-wired.network
//   - The orchestrator-side "push manifest to a fleet of VMs"
//     workflow lives in the existing orchpb Pancake service.
//     pancake-build-server produces the manifest; orchpb pushes it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: build.proto

package buildpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PancakeBuilder_BuildLayer_FullMethodName      = "/pancake.build.v1.PancakeBuilder/BuildLayer"
	PancakeBuilder_LookupLayer_FullMethodName     = "/pancake.build.v1.PancakeBuilder/LookupLayer"
	PancakeBuilder_BuildGeneration_FullMethodName = "/pancake.build.v1.PancakeBuilder/BuildGeneration"
	PancakeBuilder_GetLayer_FullMethodName        = "/pancake.build.v1.PancakeBuilder/GetLayer"
	PancakeBuilder_UploadBlob_FullMethodName      = "/pancake.build.v1.PancakeBuilder/UploadBlob"
	PancakeBuilder_ListLayers_FullMethodName      = "/pancake.build.v1.PancakeBuilder/ListLayers"
	PancakeBuilder_BuildImage_FullMethodName      = "/pancake.build.v1.PancakeBuilder/BuildImage"
)

// PancakeBuilderClient is the client API for PancakeBuilder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PancakeBuilderClient interface {
	// BuildLayer returns the canonical artifact for `spec`, building it
	// on demand if not cached. Idempotent. Synchronous: large package
	// sets can take seconds (apt fetch + mkfs.ext4 + veritysetup); use
	// a generous client deadline (>= 60s).
	BuildLayer(ctx context.Context, in *BuildLayerRequest, opts ...grpc.CallOption) (*LayerHandle, error)
	// LookupLayer is the cache-only variant: returns NOT_FOUND if the
	// server hasn't built this spec before. Useful for an orchestrator
	// assembling a generation manifest without paying build cost.
	LookupLayer(ctx context.Context, in *LookupLayerRequest, opts ...grpc.CallOption) (*LayerHandle, error)
	// BuildGeneration is BuildLayer many-at-once + assembles a signed
	// GenerationManifest ready to push via orchpb.Pancake.Update.
	// Layers are built/looked up in parallel server-side; the response
	// includes a LayerHandle for each so callers can prefetch missing
	// bytes via GetLayer at the destination.
	BuildGeneration(ctx context.Context, in *BuildGenerationRequest, opts ...grpc.CallOption) (*GenerationManifest, error)
	// GetLayer streams artifact bytes for a previously built layer.
	// Identified by roothash (canonical). Use BuildLayer/LookupLayer to
	// resolve a spec → roothash first.
	GetLayer(ctx context.Context, in *GetLayerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayerChunk], error)
	// UploadBlob streams arbitrary bytes (a kernel bzImage, a modules
	// tarball, a pancaked binary) and returns the sha256. The returned
	// digest is then referenced from a LayerSpec's synthetic variant.
	// Idempotent: re-uploading the same bytes returns the same digest
	// and writes nothing.
	UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BlobChunk, BlobReference], error)
	// ListLayers enumerates the cache. Optional name filter. No
	// pagination yet — caches stay in the low thousands.
	ListLayers(ctx context.Context, in *ListLayersRequest, opts ...grpc.CallOption) (*ListLayersResponse, error)
	// BuildImage is the operator-facing one-shot RPC: take a recipe
	// (packages + already-uploaded blobs + assembly knobs), build all
	// referenced layers (calling BuildGeneration internally), pack
	// the disk image + initramfs + UKI + EFI disk, sign via
	// pancake-sign (when the server has --sign-addr set), and stream
	// the resulting artifacts back. Replaces the client-side
	// assembly that used to live in cmd/pancake/bootstrap_builder.go.
	BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildImageChunk], error)
}

type pancakeBuilderClient struct {
	cc grpc.ClientConnInterface
}

func NewPancakeBuilderClient(cc grpc.ClientConnInterface) PancakeBuilderClient {
	return &pancakeBuilderClient{cc}
}

func (c *pancakeBuilderClient) BuildLayer(ctx context.Context, in *BuildLayerRequest, opts ...grpc.CallOption) (*LayerHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayerHandle)
	err := c.cc.Invoke(ctx, PancakeBuilder_BuildLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeBuilderClient) LookupLayer(ctx context.Context, in *LookupLayerRequest, opts ...grpc.CallOption) (*LayerHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayerHandle)
	err := c.cc.Invoke(ctx, PancakeBuilder_LookupLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeBuilderClient) BuildGeneration(ctx context.Context, in *BuildGenerationRequest, opts ...grpc.CallOption) (*GenerationManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationManifest)
	err := c.cc.Invoke(ctx, PancakeBuilder_BuildGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeBuilderClient) GetLayer(ctx context.Context, in *GetLayerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayerChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PancakeBuilder_ServiceDesc.Streams[0], PancakeBuilder_GetLayer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLayerRequest, LayerChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_GetLayerClient = grpc.ServerStreamingClient[LayerChunk]

func (c *pancakeBuilderClient) UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BlobChunk, BlobReference], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PancakeBuilder_ServiceDesc.Streams[1], PancakeBuilder_UploadBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BlobChunk, BlobReference]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_UploadBlobClient = grpc.ClientStreamingClient[BlobChunk, BlobReference]

func (c *pancakeBuilderClient) ListLayers(ctx context.Context, in *ListLayersRequest, opts ...grpc.CallOption) (*ListLayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLayersResponse)
	err := c.cc.Invoke(ctx, PancakeBuilder_ListLayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeBuilderClient) BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildImageChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PancakeBuilder_ServiceDesc.Streams[2], PancakeBuilder_BuildImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildImageRequest, BuildImageChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_BuildImageClient = grpc.ServerStreamingClient[BuildImageChunk]

// PancakeBuilderServer is the server API for PancakeBuilder service.
// All implementations must embed UnimplementedPancakeBuilderServer
// for forward compatibility.
type PancakeBuilderServer interface {
	// BuildLayer returns the canonical artifact for `spec`, building it
	// on demand if not cached. Idempotent. Synchronous: large package
	// sets can take seconds (apt fetch + mkfs.ext4 + veritysetup); use
	// a generous client deadline (>= 60s).
	BuildLayer(context.Context, *BuildLayerRequest) (*LayerHandle, error)
	// LookupLayer is the cache-only variant: returns NOT_FOUND if the
	// server hasn't built this spec before. Useful for an orchestrator
	// assembling a generation manifest without paying build cost.
	LookupLayer(context.Context, *LookupLayerRequest) (*LayerHandle, error)
	// BuildGeneration is BuildLayer many-at-once + assembles a signed
	// GenerationManifest ready to push via orchpb.Pancake.Update.
	// Layers are built/looked up in parallel server-side; the response
	// includes a LayerHandle for each so callers can prefetch missing
	// bytes via GetLayer at the destination.
	BuildGeneration(context.Context, *BuildGenerationRequest) (*GenerationManifest, error)
	// GetLayer streams artifact bytes for a previously built layer.
	// Identified by roothash (canonical). Use BuildLayer/LookupLayer to
	// resolve a spec → roothash first.
	GetLayer(*GetLayerRequest, grpc.ServerStreamingServer[LayerChunk]) error
	// UploadBlob streams arbitrary bytes (a kernel bzImage, a modules
	// tarball, a pancaked binary) and returns the sha256. The returned
	// digest is then referenced from a LayerSpec's synthetic variant.
	// Idempotent: re-uploading the same bytes returns the same digest
	// and writes nothing.
	UploadBlob(grpc.ClientStreamingServer[BlobChunk, BlobReference]) error
	// ListLayers enumerates the cache. Optional name filter. No
	// pagination yet — caches stay in the low thousands.
	ListLayers(context.Context, *ListLayersRequest) (*ListLayersResponse, error)
	// BuildImage is the operator-facing one-shot RPC: take a recipe
	// (packages + already-uploaded blobs + assembly knobs), build all
	// referenced layers (calling BuildGeneration internally), pack
	// the disk image + initramfs + UKI + EFI disk, sign via
	// pancake-sign (when the server has --sign-addr set), and stream
	// the resulting artifacts back. Replaces the client-side
	// assembly that used to live in cmd/pancake/bootstrap_builder.go.
	BuildImage(*BuildImageRequest, grpc.ServerStreamingServer[BuildImageChunk]) error
	mustEmbedUnimplementedPancakeBuilderServer()
}

// UnimplementedPancakeBuilderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPancakeBuilderServer struct{}

func (UnimplementedPancakeBuilderServer) BuildLayer(context.Context, *BuildLayerRequest) (*LayerHandle, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildLayer not implemented")
}
func (UnimplementedPancakeBuilderServer) LookupLayer(context.Context, *LookupLayerRequest) (*LayerHandle, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupLayer not implemented")
}
func (UnimplementedPancakeBuilderServer) BuildGeneration(context.Context, *BuildGenerationRequest) (*GenerationManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildGeneration not implemented")
}
func (UnimplementedPancakeBuilderServer) GetLayer(*GetLayerRequest, grpc.ServerStreamingServer[LayerChunk]) error {
	return status.Error(codes.Unimplemented, "method GetLayer not implemented")
}
func (UnimplementedPancakeBuilderServer) UploadBlob(grpc.ClientStreamingServer[BlobChunk, BlobReference]) error {
	return status.Error(codes.Unimplemented, "method UploadBlob not implemented")
}
func (UnimplementedPancakeBuilderServer) ListLayers(context.Context, *ListLayersRequest) (*ListLayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLayers not implemented")
}
func (UnimplementedPancakeBuilderServer) BuildImage(*BuildImageRequest, grpc.ServerStreamingServer[BuildImageChunk]) error {
	return status.Error(codes.Unimplemented, "method BuildImage not implemented")
}
func (UnimplementedPancakeBuilderServer) mustEmbedUnimplementedPancakeBuilderServer() {}
func (UnimplementedPancakeBuilderServer) testEmbeddedByValue()                        {}

// UnsafePancakeBuilderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PancakeBuilderServer will
// result in compilation errors.
type UnsafePancakeBuilderServer interface {
	mustEmbedUnimplementedPancakeBuilderServer()
}

func RegisterPancakeBuilderServer(s grpc.ServiceRegistrar, srv PancakeBuilderServer) {
	// If the following call panics, it indicates UnimplementedPancakeBuilderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PancakeBuilder_ServiceDesc, srv)
}

func _PancakeBuilder_BuildLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeBuilderServer).BuildLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PancakeBuilder_BuildLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeBuilderServer).BuildLayer(ctx, req.(*BuildLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PancakeBuilder_LookupLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeBuilderServer).LookupLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PancakeBuilder_LookupLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeBuilderServer).LookupLayer(ctx, req.(*LookupLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PancakeBuilder_BuildGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeBuilderServer).BuildGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PancakeBuilder_BuildGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeBuilderServer).BuildGeneration(ctx, req.(*BuildGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PancakeBuilder_GetLayer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLayerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PancakeBuilderServer).GetLayer(m, &grpc.GenericServerStream[GetLayerRequest, LayerChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_GetLayerServer = grpc.ServerStreamingServer[LayerChunk]

func _PancakeBuilder_UploadBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PancakeBuilderServer).UploadBlob(&grpc.GenericServerStream[BlobChunk, BlobReference]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_UploadBlobServer = grpc.ClientStreamingServer[BlobChunk, BlobReference]

func _PancakeBuilder_ListLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeBuilderServer).ListLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PancakeBuilder_ListLayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeBuilderServer).ListLayers(ctx, req.(*ListLayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PancakeBuilder_BuildImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PancakeBuilderServer).BuildImage(m, &grpc.GenericServerStream[BuildImageRequest, BuildImageChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PancakeBuilder_BuildImageServer = grpc.ServerStreamingServer[BuildImageChunk]

// PancakeBuilder_ServiceDesc is the grpc.ServiceDesc for PancakeBuilder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PancakeBuilder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pancake.build.v1.PancakeBuilder",
	HandlerType: (*PancakeBuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildLayer",
			Handler:    _PancakeBuilder_BuildLayer_Handler,
		},
		{
			MethodName: "LookupLayer",
			Handler:    _PancakeBuilder_LookupLayer_Handler,
		},
		{
			MethodName: "BuildGeneration",
			Handler:    _PancakeBuilder_BuildGeneration_Handler,
		},
		{
			MethodName: "ListLayers",
			Handler:    _PancakeBuilder_ListLayers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLayer",
			Handler:       _PancakeBuilder_GetLayer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadBlob",
			Handler:       _PancakeBuilder_UploadBlob_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BuildImage",
			Handler:       _PancakeBuilder_BuildImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "build.proto",
}
