// pancake-os orchestrator protocol.
//
// The wire is dead simple: the manifest IS the contract. The VM keeps
// its layer cache (kit/repo/) populated by whatever means (bootstrap,
// pancake install, future deterministic-build path). The orchestrator
// only ever exchanges the *signed manifest* for one generation.
//
//   GetCurrentManifest()  →  what the VM is running right now
//   Update(Manifest)       →  apply the supplied signed manifest
//
// On Update, the VM verifies sig + counter + presence of every layer
// the manifest references. Missing layers cause the call to fail with
// a clear list — getting layers onto the VM is out-of-band (kit was
// pre-shipped at bootstrap, or future work: VM rebuilds from apt).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/orchpb/pancake.proto

package orchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pancake_GetCurrentManifest_FullMethodName = "/pancake.v1.Pancake/GetCurrentManifest"
	Pancake_Update_FullMethodName             = "/pancake.v1.Pancake/Update"
	Pancake_Attest_FullMethodName             = "/pancake.v1.Pancake/Attest"
	Pancake_ActivateCredential_FullMethodName = "/pancake.v1.Pancake/ActivateCredential"
	Pancake_AttestSEVSNP_FullMethodName       = "/pancake.v1.Pancake/AttestSEVSNP"
)

// PancakeClient is the client API for Pancake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PancakeClient interface {
	// GetCurrentManifest returns the manifest of the generation that
	// `current` symlinks to (i.e., what the VM is "supposed to be on";
	// not necessarily what it's actively running, since `pancake swap`
	// may not have been called yet).
	GetCurrentManifest(ctx context.Context, in *GetCurrentManifestRequest, opts ...grpc.CallOption) (*Manifest, error)
	// Update accepts a new signed manifest. The VM verifies, checks
	// layer presence, and atomically writes generations/<id>/ on success.
	// It does NOT flip the current symlink; the caller (or a separate
	// pancake swap) does that. This keeps Update purely additive — a
	// failed apply leaves no observable change, and a successful apply
	// costs nothing until explicitly activated.
	Update(ctx context.Context, in *Manifest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Attest produces a TPM2 quote over the requested PCRs, signed by
	// the per-boot AK that pancaked provisioned at startup. Verifier:
	//   - validates quote signature against AttestResponse.ak_pub
	//   - confirms AK ownership against EK (compare ek_pub to the
	//     value enrolled at `pancake enroll` time; optionally run
	//     credential activation for cryptographic binding)
	//   - compares PCR digests against expected (computed from the
	//     generation manifest the verifier knows it pushed)
	//
	// Returns Unavailable if the host has no TPM (then attestation is
	// off and the orchestrator falls back to other trust signals).
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error)
	// ActivateCredential cryptographically proves the AK lives in the
	// same TPM as the enrolled EK. Verifier flow:
	//  1. Get AK pub + EK pub + AK name from a prior Attest()
	//  2. Generate a random secret S
	//  3. tpm2_makecredential -e ek.pub -n ak.name -s S -o blob
	//  4. ActivateCredential(blob) → S' from the VM's TPM
	//  5. If S == S' the AK is bound to that EK (the encryption is
	//     keyed to AK.name, only an activation by a TPM holding both
	//     EK and AK can produce the original secret).
	ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error)
	// AttestSEVSNP returns an AMD SEV-SNP attestation report bound to
	// the supplied nonce (placed in the report's REPORT_DATA field).
	// Available only inside SNP-enabled VMs (requires /dev/sev-guest).
	// Verifier fetches the VCEK certificate from AMD KDS, validates
	// the cert chain to the AMD Root Key, verifies the report
	// signature with VCEK, then compares MEASUREMENT against the
	// expected launch digest (computed from the kit's UKI bytes).
	// Returns Unavailable on non-SNP hosts.
	//
	// Complementary to Attest: SNP attests the *VM launch chain*
	// (firmware, kernel, initrd) against AMD-rooted hardware identity,
	// while Attest attests the running pancake-os state (PCR 13/14,
	// generation manifest) against the per-VM TPM. `pancake attest
	// --mode=both` runs both for defense in depth.
	AttestSEVSNP(ctx context.Context, in *AttestSEVSNPRequest, opts ...grpc.CallOption) (*AttestSEVSNPResponse, error)
}

type pancakeClient struct {
	cc grpc.ClientConnInterface
}

func NewPancakeClient(cc grpc.ClientConnInterface) PancakeClient {
	return &pancakeClient{cc}
}

func (c *pancakeClient) GetCurrentManifest(ctx context.Context, in *GetCurrentManifestRequest, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, Pancake_GetCurrentManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeClient) Update(ctx context.Context, in *Manifest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Pancake_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestResponse)
	err := c.cc.Invoke(ctx, Pancake_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeClient) ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateCredentialResponse)
	err := c.cc.Invoke(ctx, Pancake_ActivateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pancakeClient) AttestSEVSNP(ctx context.Context, in *AttestSEVSNPRequest, opts ...grpc.CallOption) (*AttestSEVSNPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestSEVSNPResponse)
	err := c.cc.Invoke(ctx, Pancake_AttestSEVSNP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PancakeServer is the server API for Pancake service.
// All implementations must embed UnimplementedPancakeServer
// for forward compatibility.
type PancakeServer interface {
	// GetCurrentManifest returns the manifest of the generation that
	// `current` symlinks to (i.e., what the VM is "supposed to be on";
	// not necessarily what it's actively running, since `pancake swap`
	// may not have been called yet).
	GetCurrentManifest(context.Context, *GetCurrentManifestRequest) (*Manifest, error)
	// Update accepts a new signed manifest. The VM verifies, checks
	// layer presence, and atomically writes generations/<id>/ on success.
	// It does NOT flip the current symlink; the caller (or a separate
	// pancake swap) does that. This keeps Update purely additive — a
	// failed apply leaves no observable change, and a successful apply
	// costs nothing until explicitly activated.
	Update(context.Context, *Manifest) (*UpdateResponse, error)
	// Attest produces a TPM2 quote over the requested PCRs, signed by
	// the per-boot AK that pancaked provisioned at startup. Verifier:
	//   - validates quote signature against AttestResponse.ak_pub
	//   - confirms AK ownership against EK (compare ek_pub to the
	//     value enrolled at `pancake enroll` time; optionally run
	//     credential activation for cryptographic binding)
	//   - compares PCR digests against expected (computed from the
	//     generation manifest the verifier knows it pushed)
	//
	// Returns Unavailable if the host has no TPM (then attestation is
	// off and the orchestrator falls back to other trust signals).
	Attest(context.Context, *AttestRequest) (*AttestResponse, error)
	// ActivateCredential cryptographically proves the AK lives in the
	// same TPM as the enrolled EK. Verifier flow:
	//  1. Get AK pub + EK pub + AK name from a prior Attest()
	//  2. Generate a random secret S
	//  3. tpm2_makecredential -e ek.pub -n ak.name -s S -o blob
	//  4. ActivateCredential(blob) → S' from the VM's TPM
	//  5. If S == S' the AK is bound to that EK (the encryption is
	//     keyed to AK.name, only an activation by a TPM holding both
	//     EK and AK can produce the original secret).
	ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error)
	// AttestSEVSNP returns an AMD SEV-SNP attestation report bound to
	// the supplied nonce (placed in the report's REPORT_DATA field).
	// Available only inside SNP-enabled VMs (requires /dev/sev-guest).
	// Verifier fetches the VCEK certificate from AMD KDS, validates
	// the cert chain to the AMD Root Key, verifies the report
	// signature with VCEK, then compares MEASUREMENT against the
	// expected launch digest (computed from the kit's UKI bytes).
	// Returns Unavailable on non-SNP hosts.
	//
	// Complementary to Attest: SNP attests the *VM launch chain*
	// (firmware, kernel, initrd) against AMD-rooted hardware identity,
	// while Attest attests the running pancake-os state (PCR 13/14,
	// generation manifest) against the per-VM TPM. `pancake attest
	// --mode=both` runs both for defense in depth.
	AttestSEVSNP(context.Context, *AttestSEVSNPRequest) (*AttestSEVSNPResponse, error)
	mustEmbedUnimplementedPancakeServer()
}

// UnimplementedPancakeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPancakeServer struct{}

func (UnimplementedPancakeServer) GetCurrentManifest(context.Context, *GetCurrentManifestRequest) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentManifest not implemented")
}
func (UnimplementedPancakeServer) Update(context.Context, *Manifest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPancakeServer) Attest(context.Context, *AttestRequest) (*AttestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedPancakeServer) ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateCredential not implemented")
}
func (UnimplementedPancakeServer) AttestSEVSNP(context.Context, *AttestSEVSNPRequest) (*AttestSEVSNPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttestSEVSNP not implemented")
}
func (UnimplementedPancakeServer) mustEmbedUnimplementedPancakeServer() {}
func (UnimplementedPancakeServer) testEmbeddedByValue()                 {}

// UnsafePancakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PancakeServer will
// result in compilation errors.
type UnsafePancakeServer interface {
	mustEmbedUnimplementedPancakeServer()
}

func RegisterPancakeServer(s grpc.ServiceRegistrar, srv PancakeServer) {
	// If the following call panics, it indicates UnimplementedPancakeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pancake_ServiceDesc, srv)
}

func _Pancake_GetCurrentManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeServer).GetCurrentManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pancake_GetCurrentManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeServer).GetCurrentManifest(ctx, req.(*GetCurrentManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pancake_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Manifest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pancake_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeServer).Update(ctx, req.(*Manifest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pancake_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pancake_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pancake_ActivateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeServer).ActivateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pancake_ActivateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeServer).ActivateCredential(ctx, req.(*ActivateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pancake_AttestSEVSNP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestSEVSNPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PancakeServer).AttestSEVSNP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pancake_AttestSEVSNP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PancakeServer).AttestSEVSNP(ctx, req.(*AttestSEVSNPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pancake_ServiceDesc is the grpc.ServiceDesc for Pancake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pancake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pancake.v1.Pancake",
	HandlerType: (*PancakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentManifest",
			Handler:    _Pancake_GetCurrentManifest_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Pancake_Update_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _Pancake_Attest_Handler,
		},
		{
			MethodName: "ActivateCredential",
			Handler:    _Pancake_ActivateCredential_Handler,
		},
		{
			MethodName: "AttestSEVSNP",
			Handler:    _Pancake_AttestSEVSNP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/orchpb/pancake.proto",
}
