// pancake-os orchestrator protocol.
//
// The wire is dead simple: the manifest IS the contract. The VM keeps
// its layer cache (kit/repo/) populated by whatever means (bootstrap,
// pancake install, future deterministic-build path). The orchestrator
// only ever exchanges the *signed manifest* for one generation.
//
//   GetCurrentManifest()  →  what the VM is running right now
//   Update(Manifest)       →  apply the supplied signed manifest
//
// On Update, the VM verifies sig + counter + presence of every layer
// the manifest references. Missing layers cause the call to fail with
// a clear list — getting layers onto the VM is out-of-band (kit was
// pre-shipped at bootstrap, or future work: VM rebuilds from apt).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/orchpb/pancake.proto

package orchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentManifestRequest) Reset() {
	*x = GetCurrentManifestRequest{}
	mi := &file_internal_orchpb_pancake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentManifestRequest) ProtoMessage() {}

func (x *GetCurrentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orchpb_pancake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentManifestRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_orchpb_pancake_proto_rawDescGZIP(), []int{0}
}

// Manifest carries the three signed-by-bootstrap files for one
// generation. The lowers TSV is included because the initramfs reads
// it without parsing TOML; sending it together avoids the receiver
// having to regenerate it (which it could, but this is simpler and the
// file is tiny — typically ~few KB).
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestToml  []byte                 `protobuf:"bytes,1,opt,name=manifest_toml,json=manifestToml,proto3" json:"manifest_toml,omitempty"` // [generation] + [[layer]]... block in TOML
	ManifestSig   []byte                 `protobuf:"bytes,2,opt,name=manifest_sig,json=manifestSig,proto3" json:"manifest_sig,omitempty"`    // RSA-SHA256 detached signature over manifest_toml
	Lowers        []byte                 `protobuf:"bytes,3,opt,name=lowers,proto3" json:"lowers,omitempty"`                                 // generations/<id>/lowers TSV sidecar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_internal_orchpb_pancake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orchpb_pancake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_internal_orchpb_pancake_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetManifestToml() []byte {
	if x != nil {
		return x.ManifestToml
	}
	return nil
}

func (x *Manifest) GetManifestSig() []byte {
	if x != nil {
		return x.ManifestSig
	}
	return nil
}

func (x *Manifest) GetLowers() []byte {
	if x != nil {
		return x.Lowers
	}
	return nil
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// installed_generation is the id parsed from the manifest, set on
	// success only.
	InstalledGeneration int32 `protobuf:"varint,1,opt,name=installed_generation,json=installedGeneration,proto3" json:"installed_generation,omitempty"`
	// missing_layer_slugs is non-empty when the manifest references
	// layers the VM doesn't have in its repo/. The caller sees them and
	// either ships them out-of-band or aborts.
	MissingLayerSlugs []string `protobuf:"bytes,2,rep,name=missing_layer_slugs,json=missingLayerSlugs,proto3" json:"missing_layer_slugs,omitempty"`
	// error is a human-readable error if the update failed for any other
	// reason (signature verification, counter rollback, parse failure).
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_internal_orchpb_pancake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orchpb_pancake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_orchpb_pancake_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResponse) GetInstalledGeneration() int32 {
	if x != nil {
		return x.InstalledGeneration
	}
	return 0
}

func (x *UpdateResponse) GetMissingLayerSlugs() []string {
	if x != nil {
		return x.MissingLayerSlugs
	}
	return nil
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_orchpb_pancake_proto protoreflect.FileDescriptor

const file_internal_orchpb_pancake_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/orchpb/pancake.proto\x12\n" +
	"pancake.v1\"\x1b\n" +
	"\x19GetCurrentManifestRequest\"j\n" +
	"\bManifest\x12#\n" +
	"\rmanifest_toml\x18\x01 \x01(\fR\fmanifestToml\x12!\n" +
	"\fmanifest_sig\x18\x02 \x01(\fR\vmanifestSig\x12\x16\n" +
	"\x06lowers\x18\x03 \x01(\fR\x06lowers\"\x89\x01\n" +
	"\x0eUpdateResponse\x121\n" +
	"\x14installed_generation\x18\x01 \x01(\x05R\x13installedGeneration\x12.\n" +
	"\x13missing_layer_slugs\x18\x02 \x03(\tR\x11missingLayerSlugs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x98\x01\n" +
	"\aPancake\x12Q\n" +
	"\x12GetCurrentManifest\x12%.pancake.v1.GetCurrentManifestRequest\x1a\x14.pancake.v1.Manifest\x12:\n" +
	"\x06Update\x12\x14.pancake.v1.Manifest\x1a\x1a.pancake.v1.UpdateResponseB?Z=github.com/sinkap/fs-pancake/tools/pancake-go/internal/orchpbb\x06proto3"

var (
	file_internal_orchpb_pancake_proto_rawDescOnce sync.Once
	file_internal_orchpb_pancake_proto_rawDescData []byte
)

func file_internal_orchpb_pancake_proto_rawDescGZIP() []byte {
	file_internal_orchpb_pancake_proto_rawDescOnce.Do(func() {
		file_internal_orchpb_pancake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_orchpb_pancake_proto_rawDesc), len(file_internal_orchpb_pancake_proto_rawDesc)))
	})
	return file_internal_orchpb_pancake_proto_rawDescData
}

var file_internal_orchpb_pancake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_orchpb_pancake_proto_goTypes = []any{
	(*GetCurrentManifestRequest)(nil), // 0: pancake.v1.GetCurrentManifestRequest
	(*Manifest)(nil),                  // 1: pancake.v1.Manifest
	(*UpdateResponse)(nil),            // 2: pancake.v1.UpdateResponse
}
var file_internal_orchpb_pancake_proto_depIdxs = []int32{
	0, // 0: pancake.v1.Pancake.GetCurrentManifest:input_type -> pancake.v1.GetCurrentManifestRequest
	1, // 1: pancake.v1.Pancake.Update:input_type -> pancake.v1.Manifest
	1, // 2: pancake.v1.Pancake.GetCurrentManifest:output_type -> pancake.v1.Manifest
	2, // 3: pancake.v1.Pancake.Update:output_type -> pancake.v1.UpdateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_orchpb_pancake_proto_init() }
func file_internal_orchpb_pancake_proto_init() {
	if File_internal_orchpb_pancake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_orchpb_pancake_proto_rawDesc), len(file_internal_orchpb_pancake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_orchpb_pancake_proto_goTypes,
		DependencyIndexes: file_internal_orchpb_pancake_proto_depIdxs,
		MessageInfos:      file_internal_orchpb_pancake_proto_msgTypes,
	}.Build()
	File_internal_orchpb_pancake_proto = out.File
	file_internal_orchpb_pancake_proto_goTypes = nil
	file_internal_orchpb_pancake_proto_depIdxs = nil
}
